// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDksS_GDFqTI9INpGVr0Hz_5YrWALxPM9Q',
    appId: '1:486441874335:web:380827eb82a06c96f8c3aa',
    messagingSenderId: '486441874335',
    projectId: 'todo-3aa81',
    authDomain: 'todo-3aa81.firebaseapp.com',
    databaseURL: 'https://todo-3aa81-default-rtdb.firebaseio.com',
    storageBucket: 'todo-3aa81.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAXBs2mvopFl3tH63sVStX90-42aHICrfQ',
    appId: '1:486441874335:android:f06a3fb0c5121021f8c3aa',
    messagingSenderId: '486441874335',
    projectId: 'todo-3aa81',
    databaseURL: 'https://todo-3aa81-default-rtdb.firebaseio.com',
    storageBucket: 'todo-3aa81.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDLUxdpcwSR3I99n_tUYh8DcOEIzb8iEQI',
    appId: '1:486441874335:ios:4d185f7c484fbddaf8c3aa',
    messagingSenderId: '486441874335',
    projectId: 'todo-3aa81',
    databaseURL: 'https://todo-3aa81-default-rtdb.firebaseio.com',
    storageBucket: 'todo-3aa81.appspot.com',
    iosBundleId: 'com.example.asana',
  );
}
